spring:
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  jmx:
    enabled: false
  jpa:
    generate-ddl: true

# disable JMX 
endpoints:
  jmx:
    enabled: false

debug: true

info:
  id: ${spring.application.name}

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
