spring:
  oauth2:
    resource:
      jwt.keyValue: |
—–BEGIN PUBLIC KEY—–
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgTkR4FdwkGKMEKUzbQxRwAREdfEC9Car
yU3hWRxBBRzpxmIj1hNDh1rBHqhYWQG/Tpsu1+iFOblPHn9sMkwg47f6h66o5ANEAjkOSh23RZYb
N8H0C/EcVLlWqs99YJUn2N59nU+bL/odk6i2ksLgy8OESfZJXUDEe0qMnc9zDyyI1lMnNW/vLJhP
69sGSoFpP0cERanNCm/+DlK14nu95RutsfC6I1wKFRRa7TM/DN/zsEeUn0BHRi4HwYP8E7f7giV8
GkRz4silB5ps9J+PdWoXc5j7juNVjyYq4zIEMaTmaLzaSduECLBQEVe/J7rcw/h858MpFA0bmYzV
Q2igzQIDAQAB
—–END PUBLIC KEY—–
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  jmx:
    enabled: false
  jpa:
    generate-ddl: true

# disable JMX 
endpoints:
  jmx:
    enabled: false

debug: true

info:
  id: ${spring.application.name}

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
