server:
  port: ${PORT:9999}

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: myapp


security:
  oauth2:
    resource:
      userInfoUri: http://auth-service:9191/uaa/user