server:
  port: ${PORT:8000}

# define the destination to which the input MessageChannel should be bound
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: myapp
          group: myapp-group
          durableSubscription: true
